#!/bin/bash

prox=/opt/Proximation
docker run -d \
    -v `pwd`/proximation.py:$prox/proximation.py \
    -v `pwd`/http.conf.in:$prox/http.conf.in \
    -v `pwd`/codado:$prox/codado \
    -v `pwd`/run-certbot:$prox/run-certbot \
    -v /var/run/docker.sock:/var/run/docker.sock \
    corydodt/nginx-proximation:latest
