#!/bin/bash

set -euo pipefail
export IFS=$'\n'

certbot_email=corydodt@gmail.com

certbot $certbot_flags certonly \
        -n \
        --agree-tos -m $certbot_email \
        --webroot -w /usr/share/nginx/html \
        --preferred-challenges http-01 \
        -d $public_hostname
certbot certificates | egrep "Certificate Name: ${public_hostname}$"
